name: Python Package Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install build dependencies
        run: |
          pip install cibuildwheel

      - name: Build wheels with cibuildwheel
        run: cibuildwheel --output-dir wheelhouse

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheelhouse/

  release-package:
    needs: build-wheels
    runs-on: ubuntu-latest

    steps:
      - name: Download built wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Extract latest changelog entry (without version header)
        run: |
          awk '/^## \[/{if (p) exit; p=1; next} p' CHANGELOG.md > latest_changelog.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body_path: "latest_changelog.md"
